name: Cats 😺

on:
    pull_request:
        types:
            - opened
            - reopened

# Permissions
permissions:
    issues: write
#
jobs:
    aCatForCreatingThePullRequest:
        name: A cat for your effort!
        runs-on: ubuntu-latest
        steps:
            - uses: ruairidhwm/action-cats@1.0.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
